version: "2"

services:
  server:
    env_file:
      - ../.env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py
    networks:
      - flasknetwork

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    image: "postgres"
    env_file:
      - ../database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - flasknetwork

  testserver:
    env_file: ../.env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.4

networks:
  flasknetwork:
    driver: bridge

volumes:
  database-data:
