"""empty message

Revision ID: 0a2676b5a583
Revises: 6e9d4856d958
Create Date: 2021-02-12 13:10:38.328905

"""

# revision identifiers, used by Alembic.
revision = '0a2676b5a583'
down_revision = '6e9d4856d958'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
